package com.github.nhirakawa.ray.tracing.shape;

public enum SceneObjectType {

  SPHERE,
  MOVING_SPHERE,
  XY_RECTANGLE,
  YZ_RECTANGLE,
  XZ_RECTANGLE,
  REVERSE_NORMALS,
  BOX,
  TRANSLATION,
  Y_ROTATION,
  CONSTANT_MEDIUM,
  AXIS_ALIGNED_BOUNDING_BOX,
  BOUNDING_VOLUME_HIERARCHY,
  SCENE_OBJECTS_LIST,

}
